version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prasad-vue-test-app
    container_name: vue-app
    ports:
      - "8087:80"
    restart: unless-stopped
